### ISSUE TITLE
Owen Evans for President

### ISSUE THREAD

**Issue by buildmaster** [JavaScript-NZ/committee-election#12]
I actually don't know if I want to nominate for this role or not, but I'm putting myself forward none the less to make sure we have a president. 

I'll bow to anyone else but also happy to take on the role as need be.

I'm Owen, and I've been a General Member of the committee since inception. I was perviously working on a startup @hoist as the technical co-founder. Working heavily in node.js and currently I'm based @8i working on their platform solution.

**Comment by bailus** [comment]
seconded.

**Comment by buildmaster** [comment]
Voted in as President
