### ISSUE TITLE
Jamie Wilson for General Member

### ISSUE THREAD

**Issue by mejamiewilson** [JavaScript-NZ/committee-election#13]
Hi Everyone, 

I'm a Senior Front End Dev and CEO of Hoist.io and absolutely love Javascript. In fact, I'd venture to suggest it's the best language ever created. I've got over 10 years experience building things with Javascript + (insert flavour of the month framework here) and want to help the community grow here in NZ. 

If you've got any questions for me, add them here :) 

Thanks

**Comment by buildmaster** [comment]
I'd vouch for @mejamiewilson and happy to second

**Comment by buildmaster** [comment]
@mejamiewilson in order to be considered for committee nominated parties must be members of the society. As such you will need to apply for membership as outlined here https://github.com/JavaScript-NZ/Society-Documentation/blob/master/Membership.md and there are membership fees associated

**Comment by buildmaster** [comment]
Not voted for as not a member in time
