### ISSUE TITLE
Samson Ootoovak for Secretary

### ISSUE THREAD

**Issue by ootoovak** [JavaScript-NZ/committee-election#14]
A bit outdated bio: http://ootoovak.com/about
My CV: https://www.linkedin.com/in/ootoovak

Been programming professionally for 8.5 years or so. I'm still mostly just doing Javascript dev in my own time but like all web developers it is always there and in my current job it will become more used as time goes on.

I have used jQuery for most of those years but in teaching at Dev Academy for a year and a half I had to get much better at the fundamentals. Since then I've played a lot in the NPM ecosystem, mostly front end and a little with Node web servers.

I enjoy learning new languages and I like the programming experience diversity that the Javascript community has as a result of it being so ubiquitous. And speaking of diversity I feel very strongly that it is something that needs to be improved in the tech community so keen to be a part of improving that in any ways that I can. The more points of view we have the better things we build. 😄 

Anyhow, that's me. Wanted to take a step into the community stuff and figured I could put my tying skills to use and help take meeting notes.

**Comment by jenofdoom** [comment]
Seconded

**Comment by PrototypeAlex** [comment]
💃

**Comment by buildmaster** [comment]
@ootoovak in order to be considered for committe nominated parties must be members of the society. As such you will need to apply for membership as outlined here https://github.com/JavaScript-NZ/Society-Documentation/blob/master/Membership.md and there are membership fees associated

**Comment by buildmaster** [comment]
Voted in as Secretary

**Comment by ootoovak** [comment]
Just going through my Github mentions and I came across this from when I was away on holiday. Just for public record it should be all paid and sorted now. Thanks for the heads up @buildmaster and @PrototypeAlex!
