### ISSUE TITLE
James Macfie for general member

### ISSUE THREAD

**Issue by jamesmacfie** [JavaScript-NZ/committee-election#15]
Hi there, I'm James.

I'm a Front End Development Team Lead at Xero and I'm looking to get more involved with the JS community.

I've been writing JS "properly" for the last 5 years or so and consider it the only programming language that I know well. Every now and again you can find me giving talks at conferences on topics about the web in general and I've got a keen interest in what you can do with hardware + JavaScript. On that note, I'm helping out this year by running a NodeBots event in Wellington for International NodeBots day.

If y'all have any other questions then let me know :)

**Comment by buildmaster** [comment]
👍 Seconding James

**Comment by buildmaster** [comment]
Voted onto committee
