### ISSUE TITLE
Jen for General Member

### ISSUE THREAD

**Issue by buildmaster** [JavaScript-NZ/committee-election#18]
Unless she wants to nominate herself for another role I'd love to make sure that @jenofdoom is involved on the committee next year. She's been amazing at getting nz.js(con); off the ground amongst lots of other help

**Comment by jenofdoom** [comment]
Thanks Owen. I'm happy to stand as a general member again.

**Comment by buildmaster** [comment]
reelected at the AGM on 17th September 2017
