### ISSUE TITLE
Alex Gibson for Treasurer

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/committee-election#3]
I nominate myself for treasurer.

I've been treasurer since the inception of the society, which was mainly due to the amount of funds coming in from nodebots was by far the largest source of our budget.

Happy to continue doing this work, but also just as happy to have the role handed over, will be there to help out if this is the case. 😄

**Comment by jenofdoom** [comment]
I second this nomination.

**Comment by buildmaster** [comment]
Voted in as Treasurer
