### ISSUE TITLE
Mike Mackenzie (veb) for General Committee Member

### ISSUE THREAD

**Issue by veb** [JavaScript-NZ/committee-election#32]
I'd absolutely love to be considered to be on the JSNZ Committee for 2019. I've spent a lot of time around these parts (since near the beginning) and would love to be someone who helps keep this community growing strong. 😎

**Comment by flamerohr** [comment]
Seconded

**Comment by gordonk** [comment]
Thirded!

**Comment by juddey** [comment]
Fourthed! (am I allowed to fourth?)

**Comment by iDanoo** [comment]
Fifth!

**Comment by annavlz** [comment]
Due to changed circumstances, Mike has withdrawn from elections.
