### ISSUE TITLE
Jen Zajac for Secretary

### ISSUE THREAD

**Issue by jenofdoom** [JavaScript-NZ/committee-election#35]
As I believe @ootoovak has expressed he is stepping away from the committee this year, I would be happy to take on the role of Secretary.

I have been a committee member since the inception of the society, and I would like to see it continue. I will be continuing to make sure that we are creating a welcoming space, as well as looking at the possibility of resurrecting nz.js(con);

**Comment by PapaBearNZ** [comment]
Seconded

**Comment by buildmaster** [comment]
passed with 10 votes
