### ISSUE TITLE
Jen Zajac for Secretary

### ISSUE THREAD

**Issue by jenofdoom** [JavaScript-NZ/committee-election#36]
I'm nominating myself to continue in the position of secretary. I've been on the committee since the inception of the society, and I'm keen to see it continue and build on our successes so far. I am chairing the next nz.js(con); conference which will be in Wellington in June 2021.

**Comment by buildmaster** [comment]
I second this nomination.

**Comment by jenofdoom** [comment]
Voted in at the AGM 29/10/2020 with 10 votes for, 0 against and 0 abstentions
