### ISSUE TITLE
Fabian Cook for Chair

### ISSUE THREAD

**Issue by fabiancook** [JavaScript-NZ/committee-election#37]
I'm nominating myself for the position of chair.

**Comment by jenofdoom** [comment]
Seconded

**Comment by fabiancook** [comment]
@jenofdoom please note the change in position

**Comment by jenofdoom** [comment]
Seconded for Chair

**Comment by jenofdoom** [comment]
Voted in at the AGM 29/10/2020 with 9 votes for, 0 against and 0 abstentions
