### ISSUE TITLE
[GM] Eduardo Rabelo

### ISSUE THREAD

**Issue by oieduardorabelo** [JavaScript-NZ/committee-election#39]
hello folks 👋

i was a volunteer in 2017 Wellington edition of nz.js(con) and since moving to Auckland in the end of the last year, I haven't had much contact with the community!

would be great to contribute more as a general member to start with

**Comment by jenofdoom** [comment]
Seconded! :)

**Comment by jenofdoom** [comment]
Voted on at the AGM 29/10/2020 with 3 votes for, 1 against and 5 abstentions - not voted in

@oieduardorabelo I don't think you were able to to make it to the AGM this time, but please do consider running again next year, thank you for your interest!
