### ISSUE TITLE
Anna Lezhikova for General Member

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/committee-election#4]
Anna is one of the Node.js meetup Wellington organisers, and has some excellent ideas and events in mostion for pushing JavaScript to underrepresented groups.

I think she'd be a great addition to the general committee.

**Comment by Kevnz** [comment]
Seconded

**Comment by dlouise64** [comment]
👍 Anna get's my vote.

**Comment by sulufiti** [comment]
Go Anna!!

**Comment by buildmaster** [comment]
Voted onto committee
