### ISSUE TITLE
[General Member] Jae Huh

### ISSUE THREAD

**Issue by ro-savage** [JavaScript-NZ/committee-election#40]
I would like to nominate Jae Huh (@jae-huh) as a General Member.

Jae joined the Javascript community through Enspiral Dev Academy 3 years ago and she has been working at an all JS-based startup that has grown rapidly.

I've seen her keen interest in bringing in new people to the community and nurturing new talent.

I believe having a JS NZ general member who has recent experience bring a grad searching for work, navigating the waters as a junior, and experiencing how to try and grow as a developer would be a valuable asset.

(Full disclosure: Jae Huh is my partner)

**Comment by jenofdoom** [comment]
Seconded :)

**Comment by jenofdoom** [comment]
Voted in at the AGM 29/10/2020 with 9 votes for, 0 against and 0 abstentions
