### ISSUE TITLE
[General Member] Julia Niall

### ISSUE THREAD

**Issue by julia-mareike** [JavaScript-NZ/committee-election#41]
Hello! I'm new ( ish ) around here, and would like to nominate myself for the general committee.

I graduated from EDA 2 years ago after a career switch, worked at Lightbox for a while and now at the AA ( the cars one ) for the past few months - javascript & node at both ✌️ 

I've gone to & talked at a few of the JS meetups, and am keen to get more involved in the community and help out where I can.

Thanks!

**Comment by Kevnz** [comment]
seconded!!!

**Comment by jenofdoom** [comment]
Voted in at the AGM 29/10/2020 with 8 votes for, 0 against and 1 abstention
