### ISSUE TITLE
Aurynn Shaw for Treasurer

### ISSUE THREAD

**Issue by jenofdoom** [JavaScript-NZ/committee-election#42]
I'd like to nominate Aurynn for treasurer of the society. Aurynn has been a general member of the society for a year and she's indicated to me that she is willing to be treasurer. As she has plenty of experience in running her own business I think she'd be a great fit to help us out with the accounts.

**Comment by fabiancook** [comment]
Seconded

**Comment by jenofdoom** [comment]
Voted in at the AGM 29/10/2020 with 10 votes for, 0 against and 0 abstentions
