### ISSUE TITLE
Chris Joe for General committee member

### ISSUE THREAD

**Issue by flamerohr** [JavaScript-NZ/committee-election#44]
I'm nominating myself as a new committee member.

**Comment by fabiancook** [comment]
Seconded

**Comment by fabiancook** [comment]
As per the AGM, a special vote was made to dissolve the society, as such a committee was not formed, and this issue can be closed. 

Thank you for nominating yourself to become a committee member, we invite you to join us as a community organiser for our Slack community, which will continue as the JavaScript New Zealand community into the future.
