### ISSUE TITLE
Comittee Nomination

### ISSUE THREAD

**Issue by MVAodhan** [JavaScript-NZ/committee-election#46]
I would like to Nominate myself for General Committee Member

**Comment by fabiancook** [comment]
Seconded

**Comment by fabiancook** [comment]
As per the AGM, a special vote was made to dissolve the society, as such a committee was not formed, and this issue can be closed. 

Thank you for nominating yourself to become a committee member, we invite you to join us as a community organiser for our Slack community, which will continue as the JavaScript New Zealand community into the future.
