### ISSUE TITLE
Suzana Melo Moraes for General committee member

### ISSUE THREAD

**Issue by suzanamelomoraes** [JavaScript-NZ/committee-election#47]
I would like to nominate myself for general committee member 🚀

**Comment by stevie-mayhew** [comment]
Seconded!

**Comment by fabiancook** [comment]
As per the AGM, a special vote was made to dissolve the society, as such a committee was not formed, and this issue can be closed. 

Thank you for nominating yourself to become a committee member, we invite you to join us as a community organiser for our Slack community, which will continue as the JavaScript New Zealand community into the future.
