### ISSUE TITLE
Stevie Mayhew for General Member

### ISSUE THREAD

**Issue by stevie-mayhew** [JavaScript-NZ/committee-election#6]
I would like to nominate myself for a general member position. I see a great opportunity for helping to drive the community forward and being more actively involved in the JavaScript New Zealand ecosystem.

A bit about me: I'm the CTO of Little Giant, a Digital Agency based out of Auckland. I run the ReactJS meetup in Auckland (although we're a bit slow on meetups). I'm also a core committer to SilverStripe for the PHP side of my world.

**Comment by PrototypeAlex** [comment]
seconded; the more meetup organisers the better 💃

**Comment by buildmaster** [comment]
Voted onto committee
