### ISSUE TITLE
Jacob Duval for General Member

### ISSUE THREAD

**Issue by frederickfogerty** [JavaScript-NZ/committee-election#7]
I would like to nominate @jladuval for General Member. He does an absolutely excellent of organising the Auckland Node.JS and AkJS meetups, and is really passionate about the development of the Javascript community. I think he would be a very valuable member to the committee, and would also be an excellent president, if he wishes to pursue that position.

**Comment by PrototypeAlex** [comment]
Seconded, @jladuval is a great JavaScript community steward, much respect!

**Comment by buildmaster** [comment]
@jladuval in order to be considered for committee nominated parties must be members of the society. As such you will need to apply for membership as outlined here https://github.com/JavaScript-NZ/Society-Documentation/blob/master/Membership.md and there are membership fees associated

**Comment by buildmaster** [comment]
Please feel free to put yourself forward again next year! Unfortunately we didn't have space for everyone
