### ISSUE TITLE
Geordie Dearns for general member

### ISSUE THREAD

**Issue by astro8891** [JavaScript-NZ/committee-election#8]

**Comment by geordidearns** [comment]
Hi all,

Just to introduce myself:

I am a graduate from Enspiral Dev Academy, now working as a developer at Sailthru (ex Carnival Mobile) with an awesome team. I mainly use Javascript as my primary working language, and would consider myself a junior (1 year professional experience) - I am excited about the javascript community, and wish to be more involved with nodebots events and anything javascript related around the Wellington Region.

Feel free to ask me any questions!

Thanks, Geordi

**Comment by astro8891** [comment]
I second Geordie

**Comment by richchurcher** [comment]
Thirded!

**Comment by buildmaster** [comment]
Please feel free to put yourself forward again next year! Unfortunately we didn't have space for everyone
