### ISSUE TITLE
Ashley Stewart for general member

### ISSUE THREAD

**Issue by astro8891** [JavaScript-NZ/committee-election#9]

**Comment by astro8891** [comment]
Hi everyone, I'm Ashley Stewart and I'm really passionate about Javascript and being involved with the community. I work daily as a Microsoft based consultant for Equinox IT which involves more and more JS as MSFT becomes 'cool again'. I have a history of organization and club/community management so I think I can contribute well. Fell free to ask me any questions

**Comment by richchurcher** [comment]
Seconded @astro8891 , good bloke :)

**Comment by buildmaster** [comment]
@astro8891 in order to be considered for committee nominated parties must be members of the society. As such you will need to apply for membership as outlined here https://github.com/JavaScript-NZ/Society-Documentation/blob/master/Membership.md and there are membership fees associated

**Comment by buildmaster** [comment]
Please feel free to put yourself forward again next year! Unfortunately we didn't have space for everyone
